// Internationalization (i18n) support with RTL

export type Language = 'en' | 'he' | 'ar' | 'fr' | 'ru';

export const RTL_LANGUAGES: Language[] = ['he', 'ar'];

export interface Translations {
  // Header
  appName: string;
  subtitle: string;
  
  // Controls
  enable: string;
  enabled: string;
  start: string;
  stop: string;
  measure: string;
  stopMeasuring: string;
  reset: string;
  
  // Inputs
  measurementInput: string;
  batchNumber: string;
  scaleReading: string;
  baseSampleWeight: string;
  biasTare: string;
  motionCorrection: string;
  
  // Metrics
  az: string;
  roll: string;
  pitch: string;
  rmsAz: string;
  rmsRoll: string;
  rmsPitch: string;
  samplingRate: string;
  confidence: string;
  measureOk: string;
  notStable: string;
  
  // Session
  ready: string;
  measuring: string;
  elapsed: string;
  samples: string;
  good: string;
  quality: string;
  
  // Result
  measurementResult: string;
  errorBand: string;
  relativeError: string;
  diagnostics: string;
  totalSamples: string;
  goodSamples: string;
  sessionRMS: string;
  sigmaMotion: string;
  sigmaScale: string;
  sigmaTotal: string;
  warning: string;
  
  // History
  measurementHistory: string;
  noMeasurements: string;
  clearAll: string;
  delete: string;
  batch: string;
  withCorrection: string;
  withoutCorrection: string;
  
  // Help
  help: string;
  helpTitle: string;
  helpOverview: string;
  helpHowItWorks: string;
  helpMath: string;
  helpMotionCorrection: string;
  helpSimpleCalculation: string;
  helpGating: string;
  helpUncertainty: string;
  helpClose: string;
  
  // Tare
  tareSection: string;
  tareReading: string;
  addTareReading: string;
  noTareSamples: string;
  biasEstimate: string;
  tareUncertainty95: string;
  tareCount: string;
  lowTareSamples: string;
  useThisTare: string;
  clearTare: string;
  manualTareOverride: string;
  useManualTare: string;
  
  // Simple Measurement
  measurementSection: string;
  addMeasurement: string;
  measurementsCollected: string;
  noMeasurementsYet: string;
  measurementStdDev: string;
  standardError: string;
  totalUncertainty1Sigma: string;
  errorBand95: string;
  mean: string;
  median: string;
  trimmedMean: string;
  trimmed: string;
  trimFraction: string;
  totalMeasurements: string;
  basedOnMeasurements: string;
  notes: string;
  invalidScaleReading: string;
  noMeasurementsToCalculate: string;
  sensorPermissionsDenied: string;
  failedToStartSensors: string;
  baseSession: string;
  finalSession: string;
  base: string;
  final: string;
  relativeChange: string;
  ratioCalculation: string;
  ratio: string;
  sigmaRatio1Sigma: string;
  errorBand95Percent: string;
  fixedValue: string;
  sessionResult: string;
  computeResult: string;
  baseValueMustBePositive: string;
  
  // Common
  grams: string;
  percent: string;
  seconds: string;
  autoGenerated: string;
  resetToAuto: string;
}

const translations: Record<Language, Translations> = {
  en: {
    appName: '🌊 Sea Sedimenter',
    subtitle: 'Shipboard Weighing Measurement',
    enable: 'Enable',
    enabled: 'Enabled',
    start: 'Start',
    stop: 'Stop',
    measure: 'Measure',
    stopMeasuring: 'Stop Measuring',
    reset: 'Reset',
    measurementInput: '📝 Measurement Input',
    batchNumber: 'Batch Number',
    scaleReading: 'Scale Reading (g)',
    baseSampleWeight: 'Base Sample Weight (g)',
    biasTare: 'Bias/Tare (g)',
    motionCorrection: 'Motion Correction',
    az: 'a_z (m/s²)',
    roll: 'Roll (°)',
    pitch: 'Pitch (°)',
    rmsAz: 'RMS a_z',
    rmsRoll: 'RMS Roll',
    rmsPitch: 'RMS Pitch',
    samplingRate: 'Rate (Hz)',
    confidence: 'Confidence',
    measureOk: 'MEASURE OK',
    notStable: 'NOT STABLE',
    ready: 'Ready',
    measuring: 'Measuring...',
    elapsed: 'Elapsed',
    samples: 'Samples',
    good: 'good',
    quality: 'Quality',
    measurementResult: 'Measurement Result',
    errorBand: 'Error Band',
    relativeError: 'Relative Error',
    diagnostics: 'Diagnostics',
    totalSamples: 'Total Samples',
    goodSamples: 'Good Samples',
    sessionRMS: 'Session RMS',
    sigmaMotion: 'σ_motion',
    sigmaScale: 'σ_scale',
    sigmaTotal: 'σ_total',
    warning: 'Warning: Measurement may be unreliable due to high motion variance.',
    measurementHistory: 'Measurement History',
    noMeasurements: 'No measurements yet',
    clearAll: 'Clear All',
    delete: 'Delete',
    batch: 'Batch',
    withCorrection: 'With correction',
    withoutCorrection: 'Without correction',
    grams: 'g',
    percent: '%',
    seconds: 's',
    autoGenerated: 'Auto-generated',
    resetToAuto: 'Reset to auto-generated',
    help: 'Help',
    helpTitle: 'Help & Documentation',
    helpOverview: 'Sea Sedimenter uses your device\'s motion sensors to improve weighing accuracy on moving ships. The app measures vertical acceleration and device orientation to gate measurements and optionally correct for motion effects.',
    helpHowItWorks: 'How It Works: 1) Enable and start sensors, 2) Enter scale reading, 3) Wait for "MEASURE OK" status, 4) Press MEASURE to start session, 5) Press STOP MEASURING when done. The app collects IMU data and scale readings, then computes a corrected result.',
    helpMath: 'Mathematics: Gravity is estimated using a low-pass filter: g_est = α·g_est + (1-α)·a_incG. Vertical acceleration: a_z = dot(a_lin, g_unit). Motion correction (if enabled): corrected = reading × g / (g + a_z). Final result uses median and trimmed mean of good samples.',
    helpMotionCorrection: 'Motion Correction: When enabled, applies physics-based correction using vertical acceleration. Formula: corrected_weight = scale_reading × 9.80665 / (9.80665 + a_z). This compensates for vertical motion effects on the scale.',
    helpSimpleCalculation: 'Simple Calculation: When motion correction is disabled, the app uses raw scale readings (minus bias/tare) with robust statistical aggregation (median, trimmed mean). This is useful when scale filtering causes phase issues or for simpler workflows.',
    helpGating: 'Gating: Measurements are gated based on RMS values. Default thresholds: RMS a_z < 0.35 m/s², RMS roll < 2.5°, RMS pitch < 2.5°. "MEASURE OK" indicates stable conditions suitable for measurement.',
    helpUncertainty: 'Uncertainty: Error bands combine motion variance (σ_motion) and scale variance (σ_scale). Total uncertainty: σ_total = √(σ_motion² + σ_scale²). 95% confidence interval: ±2×σ_total. Higher motion variance increases uncertainty.',
    helpClose: 'Close',
  },
  he: {
    appName: '🌊 מדידת משקל ימית',
    subtitle: 'מדידת משקל על סיפון',
    enable: 'הפעל',
    enabled: 'מופעל',
    start: 'התחל',
    stop: 'עצור',
    measure: 'מדוד',
    stopMeasuring: 'עצור מדידה',
    reset: 'איפוס',
    measurementInput: '📝 קלט מדידה',
    batchNumber: 'מספר אצווה',
    scaleReading: 'קריאת מאזניים (גרם)',
    baseSampleWeight: 'משקל דגימה בסיסי (גרם)',
    biasTare: 'הטיה/טרה (גרם)',
    motionCorrection: 'תיקון תנועה',
    az: 'a_z (מ/שנ²)',
    roll: 'גלגול (°)',
    pitch: 'עלרוד (°)',
    rmsAz: 'RMS a_z',
    rmsRoll: 'RMS גלגול',
    rmsPitch: 'RMS עלרוד',
    samplingRate: 'קצב (הרץ)',
    confidence: 'ביטחון',
    measureOk: 'מדידה תקינה',
    notStable: 'לא יציב',
    ready: 'מוכן',
    measuring: 'מודד...',
    elapsed: 'זמן שחלף',
    samples: 'דגימות',
    good: 'טובות',
    quality: 'איכות',
    measurementResult: 'תוצאת מדידה',
    errorBand: 'טווח שגיאה',
    relativeError: 'שגיאה יחסית',
    diagnostics: 'אבחון',
    totalSamples: 'סה"כ דגימות',
    goodSamples: 'דגימות טובות',
    sessionRMS: 'RMS מפגישה',
    sigmaMotion: 'σ_תנועה',
    sigmaScale: 'σ_מאזניים',
    sigmaTotal: 'σ_סה"כ',
    warning: 'אזהרה: המדידה עלולה להיות לא אמינה עקב שונות תנועה גבוהה.',
    measurementHistory: 'היסטוריית מדידות',
    noMeasurements: 'אין מדידות עדיין',
    clearAll: 'נקה הכל',
    delete: 'מחק',
    batch: 'אצווה',
    withCorrection: 'עם תיקון',
    withoutCorrection: 'ללא תיקון',
    grams: 'גרם',
    percent: '%',
    seconds: 'שנ',
    autoGenerated: 'נוצר אוטומטית',
    resetToAuto: 'איפוס לאוטומטי',
    tareSection: 'איסוף טרה',
    tareReading: 'קריאת טרה',
    addTareReading: 'הוסף קריאת טרה',
    noTareSamples: 'אין דגימות טרה עדיין',
    biasEstimate: 'הערכת הטיה',
    tareUncertainty95: 'אי-ודאות טרה',
    tareCount: 'מספר טרה',
    lowTareSamples: 'דגימות טרה נמוכות (מומלץ 5+)',
    useThisTare: 'השתמש בטרה זו',
    clearTare: 'נקה טרה',
    manualTareOverride: 'עקיפת טרה ידנית',
    useManualTare: 'השתמש בטרה ידנית',
    measurementSection: 'סשן מדידה',
    addMeasurement: 'הוסף מדידה',
    measurementsCollected: 'מדידות שנאספו',
    noMeasurementsYet: 'אין מדידות עדיין',
    measurementStdDev: 'σ מדידה',
    standardError: 'שגיאה סטנדרטית (SE)',
    totalUncertainty1Sigma: 'אי-ודאות כוללת (1σ)',
    errorBand95: 'טווח שגיאה (95%)',
    fixedValue: 'ערך קבוע',
    sessionResult: 'תוצאת סשן',
    computeResult: 'חשב תוצאה',
    baseValueMustBePositive: 'ערך הבסיס חייב להיות חיובי (לא ניתן לחלק באפס)',
    baseSession: 'סשן בסיס',
    finalSession: 'סשן סופי',
    base: 'בסיס',
    final: 'סופי',
    relativeChange: 'שינוי יחסי',
    ratioCalculation: 'חישוב יחס',
    ratio: 'יחס',
    sigmaRatio1Sigma: 'σ יחס (1σ)',
    errorBand95Percent: 'טווח שגיאה (95%)',
    mean: 'ממוצע',
    median: 'חציון',
    trimmedMean: 'ממוצע מקוצץ',
    trimmed: 'מקוצץ',
    trimFraction: 'קיצוץ',
    totalMeasurements: 'סה"כ מדידות',
    basedOnMeasurements: 'מבוסס על',
    notes: 'הערות',
    invalidScaleReading: 'קריאת מאזניים לא תקינה. חייב להיות מספר חיובי.',
    noMeasurementsToCalculate: 'אין מדידות לחישוב. הוסף לפחות מדידה אחת.',
    sensorPermissionsDenied: 'הרשאות חיישנים נדחו. אנא אפשר בהגדרות הדפדפן.',
    failedToStartSensors: 'הפעלת חיישנים נכשלה. בדוק הרשאות ותמיכת מכשיר.',
    help: 'עזרה',
    helpTitle: 'עזרה ותיעוד',
    helpOverview: 'מדידת משקל ימית משתמשת בחיישני התנועה של המכשיר לשיפור דיוק שקילה על ספינות בתנועה. האפליקציה מודדת תאוצה אנכית וכיוון המכשיר לסנן מדידות ולתקן (אופציונלי) השפעות תנועה.',
    helpHowItWorks: 'איך זה עובד: 1) הפעל והתחל חיישנים, 2) הזן קריאת מאזניים, 3) המתן ל-"מדידה תקינה", 4) לחץ מדוד להתחלת מפגש, 5) לחץ עצור מדידה כשסיימת. האפליקציה אוספת נתוני IMU וקריאות מאזניים, ואז מחשבת תוצאה מתוקנת.',
    helpMath: 'מתמטיקה: כוח הכבידה מוערך באמצעות מסנן מעבר נמוך: g_est = α·g_est + (1-α)·a_incG. תאוצה אנכית: a_z = dot(a_lin, g_unit). תיקון תנועה (אם מופעל): corrected = reading × g / (g + a_z). התוצאה הסופית משתמשת בחציון וממוצע מקוצץ של דגימות טובות.',
    helpMotionCorrection: 'תיקון תנועה: כשמופעל, מחיל תיקון מבוסס פיזיקה באמצעות תאוצה אנכית. נוסחה: corrected_weight = scale_reading × 9.80665 / (9.80665 + a_z). זה מפצה על השפעות תנועה אנכית על המאזניים.',
    helpSimpleCalculation: 'חישוב פשוט: כשתיקון תנועה מושבת, האפליקציה משתמשת בקריאות מאזניים גולמיות (פחות הטיה/טרה) עם צבירה סטטיסטית חזקה (חציון, ממוצע מקוצץ). זה שימושי כשיש בעיות פאזה או לעבודה פשוטה יותר.',
    helpGating: 'סינון: מדידות מסוננות על בסיס ערכי RMS. ספים ברירת מחדל: RMS a_z < 0.35 מ/שנ², RMS גלגול < 2.5°, RMS עלרוד < 2.5°. "מדידה תקינה" מציין תנאים יציבים מתאימים למדידה.',
    helpUncertainty: 'אי-ודאות: פסי שגיאה משלבים שונות תנועה (σ_motion) ושונות מאזניים (σ_scale). אי-ודאות כוללת: σ_total = √(σ_motion² + σ_scale²). רווח ביטחון 95%: ±2×σ_total. שונות תנועה גבוהה מגדילה אי-ודאות.',
    helpClose: 'סגור',
  },
  ar: {
    appName: '🌊 مقياس الرواسب البحري',
    subtitle: 'قياس الوزن على متن السفينة',
    enable: 'تفعيل',
    enabled: 'مفعل',
    start: 'ابدأ',
    stop: 'توقف',
    measure: 'قياس',
    stopMeasuring: 'إيقاف القياس',
    reset: 'إعادة تعيين',
    measurementInput: '📝 إدخال القياس',
    batchNumber: 'رقم الدفعة',
    scaleReading: 'قراءة الميزان (جم)',
    baseSampleWeight: 'وزن العينة الأساسي (جم)',
    biasTare: 'الانحياز/التعريض (جم)',
    motionCorrection: 'تصحيح الحركة',
    az: 'a_z (م/ث²)',
    roll: 'الدوران (°)',
    pitch: 'الميل (°)',
    rmsAz: 'RMS a_z',
    rmsRoll: 'RMS الدوران',
    rmsPitch: 'RMS الميل',
    samplingRate: 'المعدل (هرتز)',
    confidence: 'الثقة',
    measureOk: 'القياس جيد',
    notStable: 'غير مستقر',
    ready: 'جاهز',
    measuring: 'جارٍ القياس...',
    elapsed: 'الوقت المنقضي',
    samples: 'العينات',
    good: 'جيدة',
    quality: 'الجودة',
    measurementResult: 'نتيجة القياس',
    errorBand: 'نطاق الخطأ',
    relativeError: 'الخطأ النسبي',
    diagnostics: 'التشخيص',
    totalSamples: 'إجمالي العينات',
    goodSamples: 'عينات جيدة',
    sessionRMS: 'RMS الجلسة',
    sigmaMotion: 'σ_الحركة',
    sigmaScale: 'σ_الميزان',
    sigmaTotal: 'σ_الإجمالي',
    warning: 'تحذير: قد يكون القياس غير موثوق بسبب تباين الحركة العالي.',
    measurementHistory: 'سجل القياسات',
    noMeasurements: 'لا توجد قياسات بعد',
    clearAll: 'مسح الكل',
    delete: 'حذف',
    batch: 'الدفعة',
    withCorrection: 'مع التصحيح',
    withoutCorrection: 'بدون تصحيح',
    errorBand95: 'نطاق الخطأ (95%)',
    fixedValue: 'القيمة الثابتة',
    sessionResult: 'نتيجة الجلسة',
    computeResult: 'حساب النتيجة',
    baseValueMustBePositive: 'يجب أن تكون قيمة الأساس موجبة (لا يمكن القسمة على صفر)',
    baseSession: 'جلسة الأساس',
    finalSession: 'جلسة النهائية',
    base: 'الأساس',
    final: 'النهائي',
    relativeChange: 'التغيير النسبي',
    ratioCalculation: 'حساب النسبة',
    ratio: 'النسبة',
    sigmaRatio1Sigma: 'σ النسبة (1σ)',
    errorBand95Percent: 'نطاق الخطأ (95%)',
    mean: 'المتوسط',
    median: 'الوسيط',
    trimmedMean: 'المتوسط المقطوع',
    grams: 'جم',
    percent: '%',
    seconds: 'ث',
    autoGenerated: 'تلقائي',
    resetToAuto: 'إعادة إلى التلقائي',
    tareSection: 'جمع التعريض',
    tareReading: 'قراءة التعريض',
    addTareReading: 'إضافة قراءة التعريض',
    noTareSamples: 'لا توجد عينات تعريض بعد',
    biasEstimate: 'تقدير الانحياز',
    tareUncertainty95: 'عدم اليقين في التعريض',
    tareCount: 'عدد التعريض',
    lowTareSamples: 'عينات تعريض منخفضة (يُنصح بـ 5+)',
    useThisTare: 'استخدم هذا التعريض',
    clearTare: 'مسح التعريض',
    manualTareOverride: 'تجاوز التعريض اليدوي',
    useManualTare: 'استخدم التعريض اليدوي',
    measurementSection: 'جلسة القياس',
    addMeasurement: 'إضافة قياس',
    measurementsCollected: 'القياسات المجمعة',
    noMeasurementsYet: 'لا توجد قياسات بعد',
    measurementStdDev: 'σ القياس',
    standardError: 'الخطأ المعياري (SE)',
    totalUncertainty1Sigma: 'عدم اليقين الإجمالي (1σ)',
    trimmed: 'مقطوع',
    trimFraction: 'كسر القطع',
    totalMeasurements: 'إجمالي القياسات',
    basedOnMeasurements: 'بناءً على',
    notes: 'ملاحظات',
    invalidScaleReading: 'قراءة الميزان غير صالحة. يجب أن يكون رقمًا موجبًا.',
    noMeasurementsToCalculate: 'لا توجد قياسات للحساب. أضف قياسًا واحدًا على الأقل.',
    sensorPermissionsDenied: 'تم رفض أذونات المستشعر. يرجى التمكين في إعدادات المتصفح.',
    failedToStartSensors: 'فشل بدء المستشعرات. تحقق من الأذونات ودعم الجهاز.',
    help: 'مساعدة',
    helpTitle: 'المساعدة والتوثيق',
    helpOverview: 'يستخدم مقياس الرواسب البحري مستشعرات الحركة في جهازك لتحسين دقة الوزن على السفن المتحركة. يقيس التطبيق التسارع العمودي واتجاه الجهاز لتصفية القياسات وتصحيح (اختياري) تأثيرات الحركة.',
    helpHowItWorks: 'كيف يعمل: 1) تفعيل وبدء المستشعرات، 2) إدخال قراءة الميزان، 3) انتظار حالة "القياس جيد"، 4) اضغط قياس لبدء الجلسة، 5) اضغط إيقاف القياس عند الانتهاء. يجمع التطبيق بيانات IMU وقراءات الميزان، ثم يحسب النتيجة المصححة.',
    helpMath: 'الرياضيات: يتم تقدير الجاذبية باستخدام مرشح تمرير منخفض: g_est = α·g_est + (1-α)·a_incG. التسارع العمودي: a_z = dot(a_lin, g_unit). تصحيح الحركة (إذا تم تفعيله): corrected = reading × g / (g + a_z). النتيجة النهائية تستخدم الوسيط والمتوسط المقطوع للعينات الجيدة.',
    helpMotionCorrection: 'تصحيح الحركة: عند التفعيل، يطبق التصحيح القائم على الفيزياء باستخدام التسارع العمودي. الصيغة: corrected_weight = scale_reading × 9.80665 / (9.80665 + a_z). هذا يعوض عن تأثيرات الحركة العمودية على الميزان.',
    helpSimpleCalculation: 'الحساب البسيط: عند تعطيل تصحيح الحركة، يستخدم التطبيق قراءات الميزان الخام (ناقص الانحياز/التعريض) مع التجميع الإحصائي القوي (الوسيط، المتوسط المقطوع). هذا مفيد عندما يسبب تصفية الميزان مشاكل الطور أو للتدفقات الأبسط.',
    helpGating: 'التصفية: يتم تصفية القياسات بناءً على قيم RMS. العتبات الافتراضية: RMS a_z < 0.35 م/ث²، RMS الدوران < 2.5°، RMS الميل < 2.5°. "القياس جيد" يشير إلى ظروف مستقرة مناسبة للقياس.',
    helpUncertainty: 'عدم اليقين: تجمع نطاقات الخطأ بين تباين الحركة (σ_motion) وتباين الميزان (σ_scale). عدم اليقين الإجمالي: σ_total = √(σ_motion² + σ_scale²). فاصل الثقة 95%: ±2×σ_total. تباين الحركة الأعلى يزيد عدم اليقين.',
    helpClose: 'إغلاق',
  },
  fr: {
    appName: '🌊 Sédimenteur Marin',
    subtitle: 'Mesure de Poids à Bord',
    enable: 'Activer',
    enabled: 'Activé',
    start: 'Démarrer',
    stop: 'Arrêter',
    measure: 'Mesurer',
    stopMeasuring: 'Arrêter la Mesure',
    reset: 'Réinitialiser',
    measurementInput: '📝 Saisie de Mesure',
    batchNumber: 'Numéro de Lot',
    scaleReading: 'Lecture Balance (g)',
    baseSampleWeight: 'Poids de Base de l\'Échantillon (g)',
    biasTare: 'Biais/Tare (g)',
    motionCorrection: 'Correction de Mouvement',
    az: 'a_z (m/s²)',
    roll: 'Roulis (°)',
    pitch: 'Tangage (°)',
    rmsAz: 'RMS a_z',
    rmsRoll: 'RMS Roulis',
    rmsPitch: 'RMS Tangage',
    samplingRate: 'Taux (Hz)',
    confidence: 'Confiance',
    measureOk: 'MESURE OK',
    notStable: 'INSTABLE',
    ready: 'Prêt',
    measuring: 'Mesure en cours...',
    elapsed: 'Temps écoulé',
    samples: 'Échantillons',
    good: 'bons',
    quality: 'Qualité',
    measurementResult: 'Résultat de Mesure',
    errorBand: 'Bande d\'Erreur',
    relativeError: 'Erreur Relative',
    diagnostics: 'Diagnostics',
    totalSamples: 'Échantillons Totaux',
    goodSamples: 'Échantillons Bons',
    sessionRMS: 'RMS de Session',
    sigmaMotion: 'σ_mouvement',
    sigmaScale: 'σ_balance',
    sigmaTotal: 'σ_total',
    warning: 'Avertissement: La mesure peut être peu fiable en raison d\'une variance de mouvement élevée.',
    measurementHistory: 'Historique des Mesures',
    noMeasurements: 'Aucune mesure pour le moment',
    clearAll: 'Tout Effacer',
    delete: 'Supprimer',
    batch: 'Lot',
    withCorrection: 'Avec correction',
    withoutCorrection: 'Sans correction',
    grams: 'g',
    percent: '%',
    seconds: 's',
    autoGenerated: 'Généré automatiquement',
    resetToAuto: 'Réinitialiser en automatique',
    tareSection: 'Collecte de Tare',
    tareReading: 'Lecture de Tare',
    addTareReading: 'Ajouter Lecture de Tare',
    noTareSamples: 'Aucun échantillon de tare',
    biasEstimate: 'Estimation du Biais',
    tareUncertainty95: 'Incertitude de Tare',
    tareCount: 'Nombre de Tare',
    lowTareSamples: 'Peu d\'échantillons de tare (recommandé 5+)',
    useThisTare: 'Utiliser Cette Tare',
    clearTare: 'Effacer Tare',
    manualTareOverride: 'Surcharge Manuelle de Tare',
    useManualTare: 'Utiliser Tare Manuelle',
    measurementSection: 'Session de Mesure',
    addMeasurement: 'Ajouter Mesure',
    measurementsCollected: 'Mesures Collectées',
    noMeasurementsYet: 'Aucune mesure',
    measurementStdDev: 'σ de Mesure',
    standardError: 'Erreur Standard (SE)',
    totalUncertainty1Sigma: 'Incertitude Totale (1σ)',
    errorBand95: 'Bande d\'Erreur (95%)',
    mean: 'Moyenne',
    median: 'Médiane',
    trimmedMean: 'Moyenne Tronquée',
    trimmed: 'tronquée',
    trimFraction: 'tronquage',
    totalMeasurements: 'Mesures Totales',
    basedOnMeasurements: 'Basé sur',
    notes: 'Notes',
    invalidScaleReading: 'Lecture de balance invalide. Doit être un nombre positif.',
    noMeasurementsToCalculate: 'Aucune mesure à calculer. Ajoutez au moins une mesure.',
    sensorPermissionsDenied: 'Autorisations des capteurs refusées. Veuillez les activer dans les paramètres du navigateur.',
    failedToStartSensors: 'Échec du démarrage des capteurs. Vérifiez les autorisations et le support de l\'appareil.',
    help: 'Aide',
    helpTitle: 'Aide et Documentation',
    helpOverview: 'Sédimenteur Marin utilise les capteurs de mouvement de votre appareil pour améliorer la précision de la pesée sur les navires en mouvement. L\'app mesure l\'accélération verticale et l\'orientation de l\'appareil pour filtrer les mesures et corriger (optionnel) les effets du mouvement.',
    helpHowItWorks: 'Fonctionnement: 1) Activer et démarrer les capteurs, 2) Entrer la lecture de la balance, 3) Attendre le statut "MESURE OK", 4) Appuyer sur MESURER pour démarrer la session, 5) Appuyer sur ARRÊTER MESURE à la fin. L\'app collecte les données IMU et les lectures de balance, puis calcule un résultat corrigé.',
    helpMath: 'Mathématiques: La gravité est estimée avec un filtre passe-bas: g_est = α·g_est + (1-α)·a_incG. Accélération verticale: a_z = dot(a_lin, g_unit). Correction de mouvement (si activée): corrected = reading × g / (g + a_z). Le résultat final utilise la médiane et la moyenne tronquée des bons échantillons.',
    helpMotionCorrection: 'Correction de Mouvement: Quand activée, applique une correction basée sur la physique utilisant l\'accélération verticale. Formule: corrected_weight = scale_reading × 9.80665 / (9.80665 + a_z). Cela compense les effets du mouvement vertical sur la balance.',
    helpSimpleCalculation: 'Calcul Simple: Quand la correction de mouvement est désactivée, l\'app utilise les lectures brutes de la balance (moins biais/tare) avec agrégation statistique robuste (médiane, moyenne tronquée). Utile quand le filtrage de la balance cause des problèmes de phase ou pour des workflows plus simples.',
    helpGating: 'Filtrage: Les mesures sont filtrées selon les valeurs RMS. Seuils par défaut: RMS a_z < 0.35 m/s², RMS Roulis < 2.5°, RMS Tangage < 2.5°. "MESURE OK" indique des conditions stables adaptées à la mesure.',
    helpUncertainty: 'Incertitude: Les bandes d\'erreur combinent la variance de mouvement (σ_motion) et la variance de balance (σ_scale). Incertitude totale: σ_total = √(σ_motion² + σ_scale²). Intervalle de confiance 95%: ±2×σ_total. Une variance de mouvement plus élevée augmente l\'incertitude.',
    helpClose: 'Fermer',
  },
  ru: {
    appName: '🌊 Морской Седиментомер',
    subtitle: 'Измерение Веса на Борту',
    enable: 'Включить',
    enabled: 'Включено',
    start: 'Старт',
    stop: 'Стоп',
    measure: 'Измерить',
    stopMeasuring: 'Остановить Измерение',
    reset: 'Сброс',
    measurementInput: '📝 Ввод Измерения',
    batchNumber: 'Номер Партии',
    scaleReading: 'Показание Весов (г)',
    baseSampleWeight: 'Базовый Вес Образца (г)',
    biasTare: 'Смещение/Тара (г)',
    motionCorrection: 'Коррекция Движения',
    az: 'a_z (м/с²)',
    roll: 'Крен (°)',
    pitch: 'Дифферент (°)',
    rmsAz: 'СКЗ a_z',
    rmsRoll: 'СКЗ Крен',
    rmsPitch: 'СКЗ Дифферент',
    samplingRate: 'Частота (Гц)',
    confidence: 'Уверенность',
    measureOk: 'ИЗМЕРЕНИЕ ОК',
    notStable: 'НЕ СТАБИЛЬНО',
    ready: 'Готов',
    measuring: 'Измерение...',
    elapsed: 'Прошло',
    samples: 'Образцы',
    good: 'хороших',
    quality: 'Качество',
    measurementResult: 'Результат Измерения',
    errorBand: 'Погрешность',
    relativeError: 'Относительная Погрешность',
    diagnostics: 'Диагностика',
    totalSamples: 'Всего Образцов',
    goodSamples: 'Хороших Образцов',
    sessionRMS: 'СКЗ Сессии',
    sigmaMotion: 'σ_движение',
    sigmaScale: 'σ_весы',
    sigmaTotal: 'σ_общее',
    warning: 'Предупреждение: Измерение может быть ненадежным из-за высокой дисперсии движения.',
    measurementHistory: 'История Измерений',
    noMeasurements: 'Пока нет измерений',
    clearAll: 'Очистить Все',
    delete: 'Удалить',
    batch: 'Партия',
    withCorrection: 'С коррекцией',
    withoutCorrection: 'Без коррекции',
    errorBand95: 'Полоса Ошибки (95%)',
    fixedValue: 'Фиксированное Значение',
    sessionResult: 'Результат Сессии',
    computeResult: 'Вычислить Результат',
    baseValueMustBePositive: 'Базовое значение должно быть положительным (деление на ноль невозможно)',
    baseSession: 'Базовая Сессия',
    finalSession: 'Финальная Сессия',
    base: 'База',
    final: 'Финал',
    relativeChange: 'Относительное Изменение',
    ratioCalculation: 'Расчет Коэффициента',
    ratio: 'Коэффициент',
    sigmaRatio1Sigma: 'σ Коэффициента (1σ)',
    errorBand95Percent: 'Полоса Ошибки (95%)',
    mean: 'Среднее',
    median: 'Медиана',
    trimmedMean: 'Усеченное Среднее',
    grams: 'г',
    percent: '%',
    seconds: 'с',
    autoGenerated: 'Автоматически',
    resetToAuto: 'Сбросить на автоматический',
    help: 'Помощь',
    helpTitle: 'Помощь и Документация',
    helpOverview: 'Морской Седиментомер использует датчики движения вашего устройства для повышения точности взвешивания на движущихся судах. Приложение измеряет вертикальное ускорение и ориентацию устройства для фильтрации измерений и (опционально) коррекции эффектов движения.',
    helpHowItWorks: 'Как это работает: 1) Включите и запустите датчики, 2) Введите показание весов, 3) Дождитесь статуса "ИЗМЕРЕНИЕ ОК", 4) Нажмите ИЗМЕРИТЬ для начала сессии, 5) Нажмите ОСТАНОВИТЬ ИЗМЕРЕНИЕ по завершении. Приложение собирает данные IMU и показания весов, затем вычисляет скорректированный результат.',
    helpMath: 'Математика: Гравитация оценивается с помощью фильтра низких частот: g_est = α·g_est + (1-α)·a_incG. Вертикальное ускорение: a_z = dot(a_lin, g_unit). Коррекция движения (если включена): corrected = reading × g / (g + a_z). Финальный результат использует медиану и усеченное среднее хороших образцов.',
    helpMotionCorrection: 'Коррекция Движения: При включении применяет физическую коррекцию с использованием вертикального ускорения. Формула: corrected_weight = scale_reading × 9.80665 / (9.80665 + a_z). Это компенсирует эффекты вертикального движения на весах.',
    helpSimpleCalculation: 'Простой Расчет: При отключенной коррекции движения приложение использует сырые показания весов (минус смещение/тара) с робастной статистической агрегацией (медиана, усеченное среднее). Полезно когда фильтрация весов вызывает фазовые проблемы или для более простых рабочих процессов.',
    helpGating: 'Фильтрация: Измерения фильтруются на основе значений СКЗ. Пороги по умолчанию: СКЗ a_z < 0.35 м/с², СКЗ Крен < 2.5°, СКЗ Дифферент < 2.5°. "ИЗМЕРЕНИЕ ОК" указывает на стабильные условия, подходящие для измерения.',
    helpUncertainty: 'Неопределенность: Полосы ошибок объединяют дисперсию движения (σ_motion) и дисперсию весов (σ_scale). Общая неопределенность: σ_total = √(σ_motion² + σ_scale²). Доверительный интервал 95%: ±2×σ_total. Более высокая дисперсия движения увеличивает неопределенность.',
    helpClose: 'Закрыть',
  },
};

class I18n {
  private currentLanguage: Language = 'en';

  constructor() {
    // Load saved language preference
    const saved = localStorage.getItem('sea-sedimenter-language') as Language;
    if (saved && translations[saved]) {
      this.currentLanguage = saved;
    } else {
      // Detect browser language
      const browserLang = navigator.language.split('-')[0];
      if (translations[browserLang as Language]) {
        this.currentLanguage = browserLang as Language;
      }
    }
    this.applyLanguage();
  }

  setLanguage(lang: Language): void {
    if (translations[lang]) {
      this.currentLanguage = lang;
      localStorage.setItem('sea-sedimenter-language', lang);
      this.applyLanguage();
      // Dispatch event for components to update
      window.dispatchEvent(new CustomEvent('languagechange', { detail: lang }));
    }
  }

  getLanguage(): Language {
    return this.currentLanguage;
  }

  isRTL(): boolean {
    return RTL_LANGUAGES.includes(this.currentLanguage);
  }

  t(key: keyof Translations): string {
    return translations[this.currentLanguage][key] || translations.en[key] || key;
  }

  private applyLanguage(): void {
    const html = document.documentElement;
    html.lang = this.currentLanguage;
    html.dir = this.isRTL() ? 'rtl' : 'ltr';
  }

  getAvailableLanguages(): { code: Language; name: string }[] {
    return [
      { code: 'en', name: 'English' },
      { code: 'he', name: 'עברית' },
      { code: 'ar', name: 'العربية' },
      { code: 'fr', name: 'Français' },
      { code: 'ru', name: 'Русский' },
    ];
  }
}

export const i18n = new I18n();

